### ISSUE TITLE
Qt client is "ugly"

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#115]
This is the adjective I get most often when people discover the Qt client. So we should work on it.

**Comment by mir3x** [comment]
something can be uglier than this ??
![image](https://user-images.githubusercontent.com/43116166/99916354-1fb7e380-2d0a-11eb-9425-c1306569253a.png)

**Comment by lmoureaux** [comment]
Heck, ask them. They're too used to Gtk :crying_cat_face:

**Comment by pranavtifr** [comment]
So, I have been recently using qt and gtk together. I think predominantly the complaint comes from the fact that, qt shows a lot more information on screen. It is great once you are used to it. But the fact remains that, people would like to switch on and off certain information, and it feels really cluttered initially.

Second factor is the defaults. qt is a great client, but I think many people are thrown off by the defaults. 

Here are my few suggestions which would make qt less "ugly". They thematically follow the notion of removing certain unnecessary addons and provide an option to remove certain elements from the interface. 


Before I start, the first thing I need to say is, the view window in qt is the best. The smooth scroll makes everything more convenient, it would be nice if the other elements dont obstruct this. 

Anyways, the first change IMO would be to change the default theme. A lot of people are thrown away by the nightstalker theme (including me). I was able to use qt only because it supports the system theme, and people who are forced to use qt quickly change themes. It is better if the first view is not nightstalker and maybe give classic to people who are used to gtk. 

Secondly, Qt likes to keep floating windows in order to not move away from the view tab. I think it is a valid and great design choice, but this need to be done better. A few changes on this front IMO would make the client "cleaner" are, 

- Remove those icons next to view, units, nations etc. They occupy space and they don't look good on nightstalker theme. In the extra space from the lack of icons, I would like a "chat" tab which turns on and off the floating chat tab. It is too inconvenient to keep on screen, and also the minimap tab which can be used to turn on and off the minimap. This lets people use the view window to the fullest. 

- There should be a setting to make the chat window not transparent. The transparency makes it more cluttered. This problem is there in the units window and the demographics window too. 

- The city window needs to be rearranged. It tries to show all the options in the same window, and it is too cluttered for people who don't use all the options. Even if you aren't going the gtk way to thematically separate the options into tabs. I think a way of hiding options like "happiness" option in qt is a good way forward.Also, governer is not that important for many players, and it occupies waaay too much space. Worklist on the side in place of governers , with happiness in the location of worklists and governer hidden away somewhere is a better option imo. 

- All the default themes have backgrounds everywhere and that can be avoided to have a few backgroundless themes. 

- The initial floating info which disappears in a few secs is too large. Adds to the feeling of clutteredness.

**Comment by lmoureaux** [comment]
Thank you @pranavtifr for your detailed suggestions! Even if there wasn't much activity on this issue, we worked on a few things. I'll only cover `NightStalker` since it's the default.

First of all the icons were replaced, and are now monochrome. There's much less visual noise. The main view looks like this:
![image](https://user-images.githubusercontent.com/22327575/103219320-a7060180-491d-11eb-84dc-8887b99be2b9.png)
I don't think icons can be removed without changing the layout, and they're really useful to click the correct button when using the mouse (as opposed to the F1-F6 keys). There's definitely enough space in that bar to add a button for the chat.

The city dialog got a heavy relifting and is now overlaid on top of the main view. It's *much* better now, and can rivalise with Gtk usability-wise. Here's a screenshot (also showing some layout glitches):
![image](https://user-images.githubusercontent.com/22327575/103219435-fd734000-491d-11eb-9933-52439a6e7b40.png)

I'll for sure keep your other comments in mind!

**Comment by pranavtifr** [comment]
That city dialog is plain drop-dead gorgeous. Kudos! Can I know which commit is this ? I would love to check this out. 

 I love the icons! I was planning to write about the icons in necrophos and decided against it. But, this is indeed much better and I agree they bring a lot of usability to the mouse users. One small quip would be to maintain the aspect ratio in the icons, the one version I seem to use retains the 1:1. But your screenshot seems to have them stretched. (is this the layout glitch you are talking about ?)
 
 Something else I would like to add regarding the transparency window point I raised earlier. I was kind of ambivalent against it since transparency gives it a more modern look. So maybe blur ? I am not sure how hard that is to implement. 
 
 One last functionality point I forgot to bring it up earlier. It would be great is we can resize the split between chat and messages window.

**Comment by lmoureaux** [comment]
> That city dialog is plain drop-dead gorgeous. Kudos! Can I know which commit is this ? I would love to check this out.

Thanks! It was PR https://github.com/longturn/freeciv21/pull/158 and is now in `master`. I still need to write the build instructions, but if you've ever used CMake before you should manage… if not, open a new issue :D

I agree with the aspect ratio for sidebar icons. I don't think it has ever been exact, but I may be wrong here.  The layout glitch I was talking about is in the city dialog, the left panel is a bit wider and the whole thing isn't centered.

Blur is hard to do, even more to do fast, but there are other ways to look "modern".

> One last functionality point I forgot to bring it up earlier. It would be great is we can resize the split between chat and messages window.

It's possible! Just double click the one you want expanded. Discoverability is crap though, you're like the 10th person asking for it.

**Comment by pranavtifr** [comment]
I meant to freely able to resize it with a drag. Rather than the fully expanded or default split like we have now with the double click. Not sure, how important that is. But given an option to hide the window, I would prefer having my own split in a bigger window. 

And thanks! I was able to compile it from master. I will check it out.

**Comment by lmoureaux** [comment]
I don't think keeping this issue open is useful since there is no clear way of resolving it. Things have been vastly improved since this was opened. Closing.
