### ISSUE TITLE
Transport and engineers disbanded after terraforming swamp

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#1515]
**Describe the bug**
I just had a Transport and a couple Engineers disbanded after terraforming shallow ocean to swamp.

**To Reproduce**
1. Put as many engineers as you can on a boat
2. Have them terraform shallow to swamp
3. Wait until they're done
4. They're gone!

**Expected behavior**
The transport gets bounced to a neighboring tile.

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 883f4de67b1476984bbceac57bc6986ce0eb4e3d
 - Ruleset: `classic`

**Comment by lmoureaux** [comment]
@daavko says we need to sentry the transport

**Comment by daavko** [comment]
More specific root cause analysis that we also discussed on Discord, but also pasted here so we don't forget about it:

Bug only happens if the transport is sentried. If you have the transport selected on TC or had made it idle before TC, the bug doesn't happen.

When processing unit actions in `unit_activity_complete()`, `check_terrain_change()` is called to do some sanity checking of a tile transformation and some other stuff. One of those is bouncing units via `bounce_unit()`. This calls the pathfinder to find available tiles to bounce to. The pathfinder, as part of its algorithm, calls `unit_can_move_to_tile()` to verify whether a move to a tile is valid. This, however, checks whether the unit's current action is `ACTIVITY_IDLE` or `ACTIVITY_GOTO`, and rejects the move as invalid with any other action. Due to the fact that the unit's action is only changed to idle at the *end* of `unit_activity_complete()`, after the unit would've been bounced, all possible paths are rejected and the unit is disbanded instead since no moves are found.

Links to the Discord conversations:
- https://discord.com/channels/378908274113904641/857992468348141578/1044342775996497951
- https://discord.com/channels/378908274113904641/753356257007501454/1044372683007197298
