### ISSUE TITLE
View -> show combat detailed information doesn't seem to do anything

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1728]
**Describe the bug**
On the View menu is an option called "show combat detailed information". It does not seem to toggle anything.

**To Reproduce**
1. Open a game
2. Select an attacking unit
3. Middle-Click on an enemy unit on a tile to see the pop up widget
4. Notice the combat information shown
5. Toggle the menu item off
6. Do steps 2 to 4 again
7. Notice the same information is shown.

**Expected behavior**
Menu options do something useful

**Screenshots**
n/a

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: master
 - Ruleset/Longturn game (if applicable): n/a

**Additional context**
None

**Comment by lmoureaux** [comment]
The menu toggles the display of this popup when combat a happens:
![image](https://user-images.githubusercontent.com/22327575/212510046-2def5fba-0e90-4ecc-b4e7-94e3582cd363.png)
Note that the popup is based on live information and can't be recalled if you're not connected during the combat, or if you disconnect and connect again.

Setting as documentation because what [this page](https://longturn.readthedocs.io/en/latest/Manuals/client-manual.html#game-menu) claims is wrong.
