### ISSUE TITLE
Should the City Dialog showing totals before waste/corruption?

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1775]
**Describe the bug**
In city dialog on the general tab, the top line for prod and trade shows the net value twice. Should show total prod and total trade along with net for each. Food does it correctly showing total food and net food.

**To Reproduce**
1. Open a game, this bug came from LT76Teams
2. Open a city dialog
3. Hover over food, notice its correct
4. Hover over prod, notice it is not correct
5. Hover over trade, notice it is not correct

**Expected behavior**
Proper display of values in the dialog

**Screenshots**
Prod should display 4 ( +3)
![image](https://user-images.githubusercontent.com/23037938/214110744-0918506f-6992-4500-a7f4-7781a46dcb06.png)

Trade should display 11 ( +8)
![image](https://user-images.githubusercontent.com/23037938/214110994-67a53e78-4866-4c86-9b42-ec32191e0ec2.png)

As food shows it correct as 10 ( +4)
![image](https://user-images.githubusercontent.com/23037938/214111080-e15b759e-4d69-4eae-be8b-203b698b6905.png)

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: master at https://github.com/longturn/freeciv21/commit/01d80246a55dec3c1ddfd116bdb615261a07a3ea, but also assume its there in v3.0-rc.2
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**

**Comment by lmoureaux** [comment]
What is displayed is with waste taken off, [as it has always been](https://github.com/freeciv/freeciv/blob/master/client/gui-gtk-4.0/citydlg.c#L1852). Since you have no food waste you don't see a difference for food. You'll start see a difference if you pay for upkeep.

If we want to change this, the code is here:

https://github.com/longturn/freeciv21/blob/01d80246a55dec3c1ddfd116bdb615261a07a3ea/client/citydlg.cpp#L870

One would need to use `citizen_output` instead of `prod`.

**Comment by jwrober** [comment]
Oh interesting. Yes I guess I would like all three to be the same in the top "row" shows max/total and then net in parenthesis.
