### ISSUE TITLE
Re-evaluate how we do .desktop and .metainfo.xml files

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1997]
**Is your feature request related to a problem? Please describe.**
As part of the creation of a flatpak package for fc21, it came up during review of our [PR](https://github.com/flathub/flathub/pull/4315) that we are not following established norms as it relates to the configuration of our `.desktop` and `.metainfo.xml` files.

1. We don't have a top level ID for the game - e.g. `net.longturn.freeciv21`. We have `net.longturn.freeciv21.client` and similar for `.server`, `.ruledit`, and `.modpack-qt`.
2. We hardcode a path to the icons that live inside of the fc21 share directory. Seems like the standard is to place them in `share/icons/hicolor/[size]/apps`

To get the flatpack to work (not approved yet), I had to do some serious hacking on the files to get the to conform. 

**Describe the solution you'd like**
I think we need to re-evaluate how we are creating and installing these files.

1. Do we create a `.directory` file for Freeciv21 so menus would show Games/Freeciv21/... and the 4 icons?
2. Start shipping the `data/icons` directory in our packages/distribution and with proper file naming put the files into `share/icons/hicolor/[size]/apps` directory.
3. Update the `.desktop` files so the game (client) is a top level ID - e.g. `net.longturn.freeciv21` and the rest of the programs are below it - e.g. `net.longturn.freeciv21.server`. Alternately we say the client is `.net.longturn.freeciv21.freeciv21`, but I think this is overkill.
4. Update the `.desktop` files to simply refer to a PNG file that now resides in `share/icons/hicolor/[size]/apps`, which means no full path. So need to change how we do `configure_file()`.
5. Update the `.metainfo.xml` files to match what we did in the `.desktop` ones.
6. Change the icon location for the `.metainfo.xml` to be local and not remote

**Describe alternatives you've considered**
What we have now "works", but isn't really cross-platform/package capable. Better to use best practices and follow established standards.

**Additional context**
None

**Comment by lmoureaux** [comment]
> We don't have a top level ID for the game - e.g. net.longturn.freeciv21. We have net.longturn.freeciv21.client and similar for .server, .ruledit, and .modpack-qt.

In my opinion this is a Flatpak problem and not a Freeciv21 problem. We could make a script that lets one call any of the apps inside the Flatpak, say `flatpak run net.longturn.freeciv21` -> client, `flatpak run net.longturn.freeciv21 server` -> server. This would live in `dist/flatpak` since deb/rpm/arch/windows all support multiple apps per package. What's the situation for snaps?

> We hardcode a path to the icons that live inside of the fc21 share directory. Seems like the standard is to place them in share/icons/hicolor/[size]/apps

The fun thing about this is that icons won't be found if you install in `/opt/freeciv21` or some other standard but non-default location. I think using Kde's ECM macros would help with most of the work items in your proposed solution -- and any downside would be shared with all of Kde.
