### ISSUE TITLE
Allow allies/team mates to see all details of units same as home nation sees

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#282]
Comes in real handy with team based games.

**Comment by pranavtifr** [comment]
Piggy backing on this since it follows the same theme. imo, we should strive for not having to share any screenshots on discord. Would be nice if we could see all the demographics info of team mate. Additional points if we could provide interface to scripts so that, people can at once print everything that is needed.

**Comment by lmoureaux** [comment]
Too big so close to a stable version

**Comment by lmoureaux** [comment]
Might be as simple as checking for teams instead of players in this block:
https://github.com/longturn/freeciv21/blob/6b1baedf7d3f3d4db67ccc9af62377d1fea24b28/server/unittools.cpp#L2834-L2843
Notice `send_packet_unit_info` vs `send_packet_unit_short_info`

**Comment by jwrober** [comment]
@psampathkumar I think we need to break out more feature requests from this issue to capture your other ideas. Please do so.
