### ISSUE TITLE
Remove hardcoded automatic unit healing

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#593]
Two reasons: it is unnecessary and it is limiting.

Unnecessary: behaviour can be mimicked exclusively using ruleset effects.

Limiting: You can't adjust the healing rate in a sensible way.

(A "quick fix" was suggested to create effect with negative healing; however, this would cause a unit in a city with, for example, 9 (out of 10) HP to begin the next turn with ***less** HP than it started, and maybe even reduce health of 100% healthy units to 66%)

**_removed the other thing_**

**Comment by lmoureaux** [comment]
What is automatic unit healing?

**Comment by Corbeau-1** [comment]
> 
> 
> What is automatic unit healing?

In a city, a unit that doesn't move for the whole turn  unconditionally regains 1/3 of its HP. In the field, it regains 1/10.

**Comment by Corbeau-1** [comment]
**Low-priority non-crucial addition**: Add another effect. `HP_Regen` heals a **percentage** of unit's HP. It would be neat if there was another effect that adds a **number** of HP.

**Comment by lmoureaux** [comment]
> **Low-priority non-crucial addition**: Add another effect type. `HP_Regen` heals a **percentage** of unit's HP. It would be neat if there was another effect that adds a **number** of HP.

This effect exists, it is called `HP_Regen`.

With `HP_Regen` and `Unit_Recover`, there is enough flexibility to move the hard-coded rules for HP recovery to the ruleset.

**Comment by lmoureaux** [comment]
The current code for automatic healing works as follows:

* `EFT_HP_REGEN` is evaluated, with a minimum of 30% for units in cities (rounded down)
* Units without `hp_loss_pct` get an additional 10%, rounded up
* Fortified units get an additional 10%, rounded up

So every unit always gets at least 10% back each turn, which translates into:
```ini
[effect_hp_regen_base]
type = "HP_Regen"
value = 10
reqs = {}

[effect_unit_recover_base]
type = "Unit_Recover"
value = 1
reqs = {
  ; Unit type HP not a multiple of 10
  ; This is important for units with less than 10 HP, otherwise they'd not get anything
}
```

This should be duplicated for fortified units.

For units in cities, one has to look at every `HP_Regen` effect and implement the `max()` manually. This makes an automatic migration of older rulesets hard since one would need to implement the `max()` in ruleset semantics. Imagine if there are 10 `HP_Regen` effects with partially overlapping requirements...

**Comment by Corbeau-1** [comment]
I'm not sure I understand. Everything is added up. Why `max()`?

**Comment by lmoureaux** [comment]
> I presume `EFT_HP_REGEN` is the sum of all ruleset regeneration effects and it is compared against the hardcoded 30% in the city?

Correct

> Were there any known effects that would break this and disable recreating previous behaviour if change is introduced? Or, to ask the question in different words: **what could possibly go wrong?** :) As far as I know, all buildings made repairs 100% so no need for a `max()`.

Good point... could migrate the 100% automatically and add a warning if not...
Or I just add a flag that keeps the old behavior.

**Comment by ec429** [comment]
I think the obvious compatibility approach here is to add an `HP_Regen_Min` effect, that the server takes the `max()` of with `EFT_HP_REGEN`, then in automigration add the effect with value 30 and reqs "in a city".
