### ISSUE TITLE
Musicset capstring is v2.6

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#716]
**Describe the bug**
In `client/audio.cpp` the musicset capability string is set to 2.6

**To Reproduce**
1. Open the file, goto line 46

**Expected behavior**
This should be 3.0 to match the soundspec.

**Screenshots**
n/a

**Platform and version (please complete the following information):**
 - OS: All
 - Freeciv21 version: master
 - Ruleset/Longturn game (if applicable): n/a

**Additional context**
docs page for musicset will need to be updated along with issue.

**Comment by lmoureaux** [comment]
Is the format different from 2.6 though?

**Comment by jwrober** [comment]
No, it is the same for legacy fc 2.6. However in fc21 file we have capstring for sound as 3.0

```
#define SOUNDSPEC_CAPSTR "+Freeciv-3.0-soundset"
#define MUSICSPEC_CAPSTR "+Freeciv-2.6-musicset"
```

**Comment by lmoureaux** [comment]
[Because it changed since 2.6](https://github.com/longturn/freeciv21/commit/a61672c8c41607696ace5e52be7f1ee29d396f31)

**Comment by lmoureaux** [comment]
As discussed elsewhere, the capstrings represent the version number of the file format. Since we didn't change the format, we inherited this from Freeciv. Changing the capstrings would put unnecessary burden on modders who would have to update their mods, simply bumping the capstring. So I think it's better to keep the old ones as long as we don't introduce major incompatibilities.

If we change the format in the future by adding optional stuff without breaking backward compatibility, we can add an optional capability (so modders can require fc21 by doing `+Freeciv-2.6-musicset +fc21-cool-feature` but mods with `+Freeciv-2.6-musicset` will also work). In capstring syntax this would be:

    #define SOUNDSPEC_CAPSTR "+Freeciv-3.0-soundset fc21-cool-feature"

Notice there is no `+` so it's optional.
