### ISSUE TITLE
Panels overlap by default

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#739]
**Describe the bug**
The default layout of the panels doesn't do any work to prevent them from overlapping, and they do overlap.

**To Reproduce**
1. Start game
2. Reduce the window width to 1280px
3. Select a settler
4. See overlapping panels

**Expected behavior**

No overlap in autoplaced panels, ever.

**Screenshots**

Notice overlap between the settler and the chat area:
![image](https://user-images.githubusercontent.com/22327575/142746311-18e17022-f6a4-4be7-8fa7-d84e92cab940.png)

**Platform and version (please complete the following information):**
 - OS: any
 - Freeciv21 version: all so far

**Comment by lmoureaux** [comment]
Solving this issue isn't super easy because the widgets like to position themselves in the mapview area. Some design work is needed to come up with a scalable layout, and some refactoring to implement it.

**Comment by jwrober** [comment]
This issue was opened up a while ago before we moved to the top bar and locked messages to the upper right corner. I wonder if we need to really worry about this one at this point. I think #1158 and #1159 if resolved would go a long way in improving the user experience. With the transparency effect as shown above, a user could change the size of the chat widget to work for their screen resolution.

**Comment by lmoureaux** [comment]
Agreed, #1265 makes this the status of this issue good enough
